# Generated by Django 2.1.3 on 2018-11-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')])),
                ('answer_text', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=20)),
                ('is_correct', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerReceived',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='DuelGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.IntegerField(default=1)),
                ('first_team_score', models.IntegerField(default=0)),
                ('second_team_score', models.IntegerField(default=0)),
                ('state', models.IntegerField(choices=[(0, 'Not started'), (1, 'Player 1 select category'), (2, 'Player 1 answer'), (3, 'Player 2 select category'), (4, 'Player 2 answers'), (5, 'Finished')], default=0)),
                ('game_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questions_removed', models.CharField(max_length=300)),
                ('games_order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.GameSession')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Normal/sequential'), (2, 'Timed')])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Quiz'),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Team'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Quiz'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Team'),
        ),
        migrations.AddField(
            model_name='duelgame',
            name='first_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='contest.GameTeam'),
        ),
        migrations.AddField(
            model_name='duelgame',
            name='second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='contest.GameTeam'),
        ),
        migrations.AddField(
            model_name='duelgame',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.GameSession'),
        ),
        migrations.AddField(
            model_name='answerreceived',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Question'),
        ),
        migrations.AddField(
            model_name='answerreceived',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Team'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('number', 'question'), ('question', 'is_correct')},
        ),
    ]
