# Generated by Django 2.1.3 on 2018-11-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='letter',
            new_name='number',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('number', 'question'), ('question', 'is_correct')},
        ),
    ]
