# Generated by Django 2.1.3 on 2018-11-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='type',
        ),
    ]
