# Generated by Django 2.1.3 on 2018-11-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20181122_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questions_removed', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score_phase_1', models.IntegerField(default=0)),
                ('score_phase_2', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='team_order',
        ),
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.CharField(default='test category', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Quiz'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Team'),
        ),
    ]
