# Generated by Django 2.1.3 on 2018-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20181127_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='device_registered',
            field=models.BooleanField(default=False),
        ),
    ]
