# Generated by Django 2.1.3 on 2018-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20181127_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duelgame',
            name='game_order',
        ),
        migrations.AddField(
            model_name='gameteam',
            name='game_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duelgame',
            name='state',
            field=models.IntegerField(choices=[(0, 'Not started'), (1, 'Category'), (2, 'Question'), (5, 'Finished')], default=0),
        ),
    ]
