# Generated by Django 2.1.3 on 2018-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20181203_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameteam',
            name='game_order',
        ),
        migrations.AddField(
            model_name='duelgame',
            name='game_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
