# Generated by Django 2.1.3 on 2018-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20181203_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelgame',
            name='selectedCategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='device_unique_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
