# Generated by Django 2.1.3 on 2018-12-09 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20181206_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duelgame',
            old_name='selectedCategory',
            new_name='selected_category',
        ),
        migrations.AddField(
            model_name='duelgame',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duelgame',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duelgame',
            name='round_log',
            field=models.CharField(default='[]', max_length=300),
        ),
        migrations.AddField(
            model_name='duelgame',
            name='round_winner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='duelgame',
            name='third_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_team', to='contest.GameTeam'),
        ),
        migrations.AddField(
            model_name='duelgame',
            name='third_team_score',
            field=models.IntegerField(default=0),
        ),
    ]
