# Generated by Django 2.1.3 on 2018-12-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_auto_20181209_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelgame',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contest.GameTeam'),
        ),
        migrations.AlterField(
            model_name='duelgame',
            name='state',
            field=models.IntegerField(choices=[(0, 'Not started'), (1, 'Category'), (2, 'Question'), (3, 'Tie'), (5, 'Finished')], default=0),
        ),
    ]
