# Generated by Django 2.1.3 on 2018-12-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20181210_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelgame',
            name='first_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='contest.GameTeam'),
        ),
        migrations.AlterField(
            model_name='duelgame',
            name='second_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='contest.GameTeam'),
        ),
    ]
