# Generated by Django 2.1.3 on 2018-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20181210_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelgame',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')], null=True),
        ),
    ]
